#!/usr/bin/env sh

mkdir -p /home/alex/images/screenshots

grim -g "$(slurp)" "/home/alex/images/screenshots/$(date --iso-8601='seconds').png"
#-e 'xclip -selection c -t image/png < $f'
notify-send '  Selection screenshot taken.'
