#!/usr/bin/env sh

mkdir -p ~/videos/screenrecs


#scrot ~/images/screenshots/$(date --iso-8601='seconds').png -m -e 'xclip -selection c -t image/png < $f'
#notify-send 'Not yet implemented'
notify-send 'Recording screen...'
ffmpeg -video_size 1366x768 -framerate 25 -f x11grab -i :0.0+0,0 ~/videos/screenrecs/vuebug.mp4
notify-send 'Screen recording saved.'
