# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig()
config.source('./themes/nord-qutebrowser.py')
c.bindings.key_mappings['<Alt+Right>'] = '<Shift-j>'
c.bindings.key_mappings['<Alt+Left>'] = '<Shift-k>'
config.bind(',k', 'spawn --userscript keep_tracks.sh')
config.bind(',c', 'spawn --userscript keep_ytchannel.sh')
c.aliases['foo'] = 'message-info foo'
