# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig()
config.source('./themes/nord-qutebrowser.py')
c.bindings.key_mappings['<Alt+Right>'] = '<Shift-j>'
c.bindings.key_mappings['<Alt+Left>'] = '<Shift-k>'
config.bind(',k', 'spawn --userscript keep_tracks.sh')
config.bind(',c', 'spawn --userscript keep_ytchannel.sh')
config.bind('<Ctrl-]>', "jseval document.getElementsByClassName('html5-main-video')[0].playbackRate = 2.5")
config.bind('<Ctrl-[>', "jseval document.getElementsByClassName('html5-main-video')[0].playbackRate = 1")
config.bind('<Ctrl-+>', "jseval document.getElementsByClassName('html5-main-video')[0].playbackRate = document.getElementsByClassName('html5-main-video')[0].playbackRate + 0.25")
config.bind('<Ctrl-->', "jseval document.getElementsByClassName('html5-main-video')[0].playbackRate = document.getElementsByClassName('html5-main-video')[0].playbackRate - 0.25")
c.aliases['foo'] = 'message-info foo'
