#!/bin/sh

notify-send "Adding a track to listen later..."

source /home/alex/.config/perso/zsh/zsh_paths

LISTEN_LATER_FILE="F_BOOKMARKS/listen_later.yml"

# Check if listen_later.yml exists, create it if not
[ -d "$F_BOOKMARKS" ] || mkdir -p "$F_BOOKMARKS"
[ -f "$LISTEN_LATER_FILE" ] || touch "$LISTEN_LATER_FILE"

# Use yt-dlp to get the channel ID
TITLE=$(yt-dlp --print title --no-playlist --skip-download "$QUTE_URL")
notify-send "to: $TITLE"

TAGS=$(yt-dlp --print tags --no-playlist --skip-download "$QUTE_URL")
URL=$(yt-dlp --print webpage_url --no-playlist --skip-download "$QUTE_URL")

yq e -i ". += [{\"title\": \"$TITLE\", \"url\": \"$URL\", \"tags\": \"$TAGS\"}]" /home/alex/notes/bookmarks/listen_later.yml

yt-dlp --no-playlist --write-thumbnail -o "thumbnail:/home/alex/notes/bookmarks/thumbs/listen/%(title)s" --skip-download "$QUTE_URL"

notify-send "Saved $TITLE"
