#!/usr/bin/env sh

selected_gif=$(nsxiv -N preview -to ~/.config/perso/colors/palette/*.gif)
selected_color=$(echo "$selected_gif" | cut -d '-' -f2)
if [[ -n $selected_color ]]; then
  echo "$selected_color" | wl-copy 
  echo "$selected_color" 
  notify-send -i "$selected_gif" " Copied color $selected_color"
fi
