# Floating menu on the currently focused output.
# Width, height and position are percentages of the workspace.
for_window [app_id="fzfmenu"] {
    floating enable
    border pixel 2
    resize set width 92 ppt height 70 ppt
    move position 4 ppt 0 ppt
    focus
}
