shopt -s expand_aliases

alias search="apt-cache search"

# some more ls aliases
alias ls='ls --color=auto'
alias ll='ls -alhF'
alias la='ls -A'
alias l='ls -CF'
alias llast='ls -Artls | tail -n1'


alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias ......='cd ../../../../../'
alias .5='cd ../../../../..'

alias 'p'='cd -'
alias d='du -sh *'

alias cdvim='cd ~/.vim'
alias editvim='vim ~/.vim/vimrc'
alias editbash='vim -p ~/.config/perso/bash_config/bashrc ~/.config/perso/bash_config/bash_aliases ~/.config/perso/bash_config/bash_funcs ~/.config/perso/bash_config/bash_specifics ~/.config/perso/bash_config/bash_vars ~/.config/perso/bash_config/profile ~/.config/perso/bash_config/bash_completion'

alias editi3='vim -p ~/.config/perso/i3/config ~/.config/perso/polybar/config ~/.config/perso/rofi/launcher.rasi ~/.config/perso/rofi/window_switcher.rasi ~/.config/perso/rofi/social.rasi ~/.config/perso/dunst/dunstrc'


#TODO: install to browser
alias torb='~/Documents/Apps/Security/tor-browser_en-US/start-tor-browser'

#TODO: Create a global config file for all these parameters
alias shortcuts='less ~/.config/perso/tools/shortcuts'
alias eshortcuts='vim ~/.config/perso/tools/shortcuts'
alias versions='~/.config/perso/tools/versions.sh'

alias c='clear'

# Colorize the grep command output for ease of use (good for log files)##
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

#Pipe to clipboad via command | copy
alias copy='xclip -sel clip'

alias path='pwd | copy'

#Random password generator
alias genpass='< /dev/urandom tr -dc A-Za-z0-9 | head -c${1:-22};echo;'


#Git aliases
alias gits='git status'
alias gita='git add -A'
alias gitc='git commit -m '
alias gitpl='git pull'
alias gitp='git push'
alias gitswitch='sed -i "s/https:\/\/github\.com\//git@github\.com:/" "$(git rev-parse --show-toplevel)"/.git/config'

#Docker aliases
alias dcu='docker-compose -f *-compose.yml up'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias docker-ip="docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "


#Check public IP
alias whatismyip="curl https://ipinfo.io/ip"

#Copy last executed docmmand to clipboard (needs X)
alias copylast="history |tail -n2 |head -n1 | cut -d ' ' -f4- | copy"
alias cl=copylast

alias listignored="find . -type f  | git check-ignore --stdin"
