shopt -s expand_aliases

# some more ls aliases
alias ls='ls --color=auto'
alias ll='ls -alhF'
alias la='ls -A'
alias l='ls -CF'
alias llast='ls -Artls | tail -n1'
alias lll='ls -Ahtls'
alias lll5='ls -Ahrtls | tail -n5 | tac'

alias f='find . -name'

alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias ......='cd ../../../../../'
alias .5='cd ../../../../..'

alias 'p'='cd -'
alias d='du -sh *'

alias cdvim='cd ~/.vim'
alias editvim='vim ~/.vim/vimrc'
alias editbyobu='vim -p ~/.byobu/color.tmux ~/.byobu/blue.tmuxtheme ~/.byobu/datetime.tmux ~/.byobu/profile.tmux ~/.byobu/keybindings.tmux ~/.byobu/.tmux.conf'
alias editbash='vim -p $F_CONFIG_BASH/bashrc $F_CONFIG_BASH/bash_aliases $F_CONFIG_BASH/bash_funcs $F_CONFIG_BASH/bash_specifics $F_CONFIG_BASH/bash_vars $F_CONFIG_BASH/profile $F_CONFIG_BASH/bash_completion $F_CONFIG_BASH/bash_paths'

alias editi3='vim -p ~/.config/perso/i3/config ~/.config/perso/polybar/config ~/.config/perso/rofi/launcher.rasi ~/.config/perso/rofi/window_switcher.rasi ~/.config/perso/rofi/social.rasi ~/.config/perso/dunst/dunstrc'

alias editansible='vim -p ~/.config/perso/environments/ansible/roles/minimal/tasks/main.yml ~/.config/perso/environments/ansible/roles/workstation/tasks/main.yml ~/.config/perso/environments/ansible/roles/desktop/tasks/main.yml ~/.config/perso/environments/ansible/roles/minimal/vars/main.yml ~/.config/perso/environments/ansible/roles/workstation/vars/main.yml ~/.config/perso/environments/ansible/roles/desktop/vars/main.yml'


#TODO: install tor browser
alias torb='~/Documents/Apps/Security/tor-browser_en-US/start-tor-browser'

#TODO: Create a global config file for all these parameters
alias versions='~/.config/perso/tools/versions.sh'

alias c='clear'

# Colorize the grep command output for ease of use (good for log files)##
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

#Pipe to clipboad via command | copy
alias copy='xclip -sel clip'

alias path='pwd | copy'

#Random password generator
alias genpass='< /dev/urandom tr -dc A-Za-z0-9 | head -c${1:-22};echo;'


#Git aliases
alias gits='git status'
alias gitd='git diff'
alias gita='git add -A'
alias gitc='git commit -m '
alias gitpl='git pull'
alias gitp='git push'
alias gitswitch='sed -i "s/https:\/\/github\.com\//git@github\.com:/" "$(git rev-parse --show-toplevel)"/.git/config'

#Task aliases
alias taska='task add'
alias taskm='task modify'

alias taskaf='task add project:flow'
alias taskafl='task add project:flow priority:L'
alias taskafm='task add project:flow priority:M'
alias taskafh='task add project:flow priority:H'


alias vitf='vit project:flow'


#Docker aliases
alias dcu='docker-compose -f *-compose.yml up'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias docker-ip="docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "


#Check public IP
alias whatismyip="curl https://ipinfo.io/ip"

#Copy last executed docmmand to clipboard (needs X)
alias copylast="history |tail -n2 |head -n1 | cut -d ' ' -f4- | copy"
alias cl=copylast

alias listignored="find . -type f  | git check-ignore --stdin"

alias dmenu=" rofi -dmenu"

