#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrdb ~/.Xresources &
killall "picom"
picom -b &
killall "dunst"
dunst &
killall "feh"
feh --bg-scale file:///home/alex/images/wallpapers/current &
killall "redshift"
redshift &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config focused_border_color  "#81a1c1"
bspc config window_gap          12

#bspc config pointer_modifier super
bspc config click_to_focus none
bspc config focus_follows_pointer true

bspc config split_ratio          0.5
bspc config single_monocle   true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a main-term desktop=^2
st -c main-term tmux &

bspc rule -a mixer state=floating sticky=on
