#!/usr/bin/env bash

cat /home/alex/.config/perso/tools/actions/data/emoji-data.txt | sed -e "s/^.*(//" | sed "s/)/ -/" | dmenu -i | sed -e "s/ -.*$//" | xclip -selection clipboard -i
notify-send "Copied `xclip -selection clipboard -o`"
