---
# tasks file for workstation

#- debug: var=links_to_create

- name: Configs git usual name
  git_config:
    name: user.name
    scope: global
    value: 'alxndrpsclt'

- name: Configs git usual email
  git_config:
    name: user.email
    scope: global
    value: 'alxndr.psclt@gmail.com'

- name: Configs git editor
  git_config:
    name: core.editor
    scope: global
    value: vim


- name: Install packages for workstation
  become: yes
  pacman:
    name:
      - python-pip
      - vim
      - htop
      - nmap
      - the_silver_searcher
      - fzf
      - vifm
      - mlocate
      - strace
      - qrencode
      - youtube-dl
    state: present

- name: Install virtualenv & cie using pip
  become: yes
  pip:
    name:
      - virtualenv
      - virtualenvwrapper
#      - terminal_velocity


        #- name: Clone personal bashconfig and other usefull configs
        #  git:
        #    repo: 'https://github.com/AlxndrPsclt/configPerso.git'
        #    dest: "{{ HOME }}/.config/perso"
        #
        #  #source $CONFIG_PERSO/tools/generateBashSpecifics.sh

- name: Clone personal vimconfig
  git:
    repo: 'https://github.com/AlxndrPsclt/dotvim.git'
    dest: "{{ HOME }}/.vim"

- name: Clone Vundle for vim plugins
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: "{{ HOME }}/.vim/bundle/Vundle.vim"


- name: Register existence of workstation config links
  stat:
    path: "{{ item.dest }}"
  loop: "{{ links_to_create }}"
  register: link_register

- name: Remove workstation config file if some default exists (not links)
  file:
    path: "{{ item.stat.path }}"
    state: absent
  loop: "{{ link_register.results }}"
  when: item.stat.islnk is defined and item.stat.islnk == False

- name: Create symbolic link for workstation config tools
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop: "{{ links_to_create }}"

- name: Register existence of workstation config links needing sudo
  stat:
    path: "{{ item.dest }}"
  loop: "{{ links_to_create_sudo }}"
  register: link_register_sudo

- name: Remove file to create links (sudo)
  file:
    path: "{{ item.stat.path }}"
    state: absent
  loop: "{{ link_register_sudo.results }}"
  when: item.stat.islnk is defined and item.stat.islnk == False

- name: Create symbolic link for workstation tools needing sudo
  become: true
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop: "{{ links_to_create_sudo }}"

- name: Create local/run directory for mpd if it does not exist
  file:
    path: "{{ ansible_env.HOME }}/.local/run/mpd"
    state: directory

- name: Copies files for network setup with systemd-networkd
  copy:
    src: {{ ansible_env.CONFIG_PERSO }}/network/*
    dest: /etc/systemd/network/
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Copies files for wifi setup with wpa_supplicant
  copy:
    src: {{ ansible_env.CONFIG_PERSO }}/wpa_supplicant/*
    dest: /etc/wpa_supplicant/
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: enable service systemd-networkd
  systemd:
    name: systemd-networkd
    scope: user
    state: started
    enabled: yes
    masked: no

- name: enable service systemd-resolved
  systemd:
    name: systemd-resolved
    scope: user
    state: started
    enabled: yes
    masked: no

- name: enable service wpa_supplicant@wlp2s0
  systemd:
    name: systemd-resolved
    scope: user
    state: started
    enabled: yes
    masked: no

- name: disable service NetworkManager
  systemd:
    name: NetworkManager
    scope: user
    enabled: no
    masked: no



- name: Allow 'wheel' group to have passwordless sudo
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^# %wheel ALL=(ALL) NOPASSWD: ALL'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Installing some software using yay
  yay:
    name:
      - byobu
      - bash-git-prompt

- name: Deactivale 'wheel' group passwordless sudo
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel ALL=(ALL) NOPASSWD: ALL'
    line: '# %wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: enable service mpd
  systemd:
    name: mpd
    scope: user
    state: started
    enabled: yes
    masked: no


