---
# tasks file for desktop

- name: Install packages for desktops
  become: yes
  pacman:
    name:
      - xorg
      - xorg-xinit
      - lightdm
      - bspwm
      - sxhkd
      - rxvt-unicode
      - xclip
    state: present

- name: Install packages for audio
  become: yes
  pacman:
    name:
      - pulseaudio
      - pulseaudio-alsa
      - bluez
      - bluez-utils
      - pulseaudio-bluetooth
      - pamixer
    state: present

- name: Install packages for desktops2B
  become: yes
  pacman:
    name:
#      - noto-fonts
      - qutebrowser
      - awesome-terminal-fonts
    state: present

- name: Install packages for desktops2C
  become: yes
  pacman:
    name:
      - libnotify
      - chromium
    state: present

- name: Install packages for desktops 3
  become: yes
  pacman:
    name:
      - zathura
      - zathura-pdf-poppler
#      - rofi
      - picom
#      - conky
      - dunst
      - redshift
      - mpv
      - pass
      - wmctrl
      - xsel
      - scrot
#      - rtorrent
      - tlp
      - feh
      - light
#      - task
#      - ffmpeg
    state: present

##Add nixshell install

- name: Allow 'wheel' group to have passwordless sudo
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^# %wheel ALL=(ALL) NOPASSWD: ALL'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Allow auto powering of bluetooth device on startup
  become: yes
  lineinfile:
    dest: /etc/bluetooth/main.conf
    state: present
    regexp: '^#AutoEnable=false'
    line: 'AutoEnable=true'

- name: Installing some software using yay
  yay:
    name:
      - ttf-oxygen-gf
      - powerline-fonts-git
#      - i3lock-fancy-git
#      - st-luke-git
#      - vit
      - lightdm-mini-greeter
      - pulsemixer

        #- name: enable service ly
        #  systemd:
        #    name: ly
        #    state: started
        #    enabled: yes
        #    masked: no
        #
- name: Deactivale 'wheel' group passwordless sudo
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel ALL=(ALL) NOPASSWD: ALL'
    line: '# %wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

    #TODO: Add xdg-handling
    #xdg-mime default org.qutebrowser.qutebrowser.desktop x-scheme-handler/http
    #xdg-mime default org.qutebrowser.qutebrowser.desktop x-scheme-handler/https
    #xdg-mime default org.pwmt.zathura.desktop application/pdf
    #xdg-mime default feh.desktop image/png
    #xdg-mime default feh.desktop image/jpg
    #




- name: Register existence of desktop config links
  stat:
    path: "{{ item.dest }}"
  loop: "{{ links_to_create }}"
  register: link_register

- name: Remove desktop config file if some default exists (not links)
  file:
    path: "{{ item.stat.path }}"
    state: absent
  loop: "{{ link_register.results }}"
  when: item.stat.islnk is defined and item.stat.islnk == False

- name: Create applications directory if it does not exist (will containing xdg-config)
  file:
    path: "{{ HOME }}/.local/share/applications"
    state: directory

- name: Create downloads directory if it does not exist
  file:
    path: "{{ HOME }}/downloads"
    state: directory

- name: Create music directory if it does not exist
  file:
    path: "{{ HOME }}/music"
    state: directory

- name: Create symbolic link for desktop config tools
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop: "{{ links_to_create }}"

- name: Create qutebrowser directory if it does not exist
  file:
    path: "{{ ansible_env.HOME }}/.local/share/qutebrowser"
    state: directory

- name: Create symbolic link for qutebrowser userscripts
  become: yes
  file:
    src: "{{ CONFIG_PERSO }}/qutebrowser/userscripts"
    dest: "{{ HOME }}/.local/share/qutebrowser/userscripts"
    state: link

- name: Create virtualenvs required for qutebrowser userscripts
  command: ~/.config/perso/qutebrowser/userscripts/virtualenvs/create_virtualenvs.sh

- name: Create file for qutebrowser log
  become: yes
  file:
    path: "/var/log/qutebrowser_scripts.log"
    state: touch
    owner: alex
    group: wheel
    mode: '0644'

- name: Create screencasting directory if it does not exist
  file:
    path: "{{ ansible_env.HOME }}/videos/screencapture"
    state: directory


    ## Clones private repos (passwords and stuff)
    #- include_vars: credentials.yml
    #
    #- name: Clone personal password vault
    #  git:
    #    repo: "https://oauth2:{{ gitlab_token }}@gitlab.com/AlxndrPsclt/password-store.git"
    #    dest: "{{ HOME }}/.password-store"
    #
    #- name: Clone personal music diggings notes
    #  git:
    #    repo: "https://oauth2:{{ gitlab_token }}@gitlab.com/AlxndrPsclt/music-diggings.git"
    #    dest: "{{ HOME }}/notes"
    #
    #- name: Clone personal wallpapers folder
    #  git:
    #    repo: "https://oauth2:{{ gitlab_token }}@gitlab.com/AlxndrPsclt/wallpapers.git"
    #    dest: "{{ HOME }}/image/wallpapers"
    #
    #- name: Clone personal tasklist
    #  git:
    #    repo: "https://oauth2:{{ gitlab_token }}@gitlab.com/AlxndrPsclt/tasks.git"
    #    dest: "{{ HOME }}/.task"
    #
