---
# tasks file for desktop
- name: Install virtualenv & cie using pip
  become: yes
  pip:
    name: ['virtualenv', 'virtualenvwrapper']

- name: Install packages for desktops
  become: yes
  pacman:
    name:
      - xorg
      - xorg-xinit
      - i3-gaps
      - rvtx-unicode
      - xclip
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - rxvt-unicode
      - powerline-fonts
      - awesome-terminal-fonts
      - mpv
      - wmctrl
      - scrot
    state: present
