---
# tasks file for desktop

- name: Install packages for desktops
  become: yes
  pacman:
    name:
      - xorg
      - xorg-xinit
      - i3-gaps
      - rxvt-unicode
      - xclip
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - pamixer
      - powerline-fonts
      - awesome-terminal-fonts
      - qutebrowser
      - chromium
      - zathura
      - zathura-pdf-poppler
      - conky
      - dunst
      - redshift
      - mpv
      - wmctrl
      - scrot
      - rtorrent
      - tlp
    state: present






- name: Register existence of desktop config links
  stat:
    path: "{{ item.dest }}"
  loop: "{{ links_to_create }}"
  register: link_register

- name: Remove desktop config file if some default exists (not links)
  file:
    path: "{{ item.stat.path }}"
    state: absent
  loop: "{{ link_register.results }}"
  when: item.stat.islnk is defined and item.stat.islnk == False

- name: Create symbolic link for desktop config tools
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop: "{{ links_to_create }}"

- name: Create qutebrowser directory if it does not exist
  file:
    path: "{{ ansible_env.HOME }}/.local/share/qutebrowser"
    state: directory

- name: Create symbolic link for qutebrowser userscripts
  become: yes
  file:
    src: "{{ CONFIG_PERSO }}/qutebrowser/userscripts"
    dest: "{{ HOME }}/.local/share/qutebrowser/userscripts"
    state: link

