#!/bin/bash

occupied_desktop=$(bspc query -T -d | jq -r .root)

if [[ "$occupied_desktop" == "null" ]]; then
  class_to_use="wikif" ;
else
  class_to_use="wiki" ;
fi

st -c "$class_to_use"  -f "Iosevka:size=24" -e ~/.config/perso/focus/focusvim "-S ~/.vim/sessions/focus.vim"

