---
# tasks file for workstation related software: this will be a computer that I use to do genreal work (as opposed to a specialised server)
- name: Install packages for classic work related tools
  become: yes
  pacman:
    name:
      - pass
    state: present

- name: Create multiple directory example
  become: yes
  file:
    path: "{{ item.dest }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - { dest: '/docker', group: 'root', mode: '0755' }
    - { dest: '/docker/src', group: 'docker', mode: '0775' }
    - { dest: '/docker/volumes', group: 'docker', mode: '0775' }
    - { dest: '/docker/configs', group: 'docker', mode: '0775' }
    - { dest: '/ansible', group: 'ansible', mode: '0775' }

