---
# tasks file for workstation

- name: Install packages for workstation
  become: yes
  pacman:
    name:
      - python-pip
    state: present


- name: Install virtualenv & cie using pip
  become: yes
  pip:
    name:
      - virtualenv
      - virtualenvwrapper
      - terminal_velocity

- name: Register existence of workstation config links
  stat:
    path: "{{ item.dest }}"
  loop: "{{ links_to_create }}"
  register: link_register

- name: Remove workstation config file if some default exists (not links)
  file:
    path: "{{ item.stat.path }}"
    state: absent
  loop: "{{ link_register.results }}"
  when: item.stat.islnk is defined and item.stat.islnk == False

- name: Create symbolic link for workstation config tools
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  become: true
  loop: "{{ links_to_create }}"

