---
# tasks file for workstation

- name: Install packages for workstation
  become: yes
  pacman:
    name:
      - python-pip
    state: present


- name: Install virtualenv & cie using pip
  become: yes
  pip:
    name:
      - virtualenv
      - virtualenvwrapper
      - terminal_velocity
