---
# tasks file for minimal
#

# Installing basic tools needed for future installs
- name: Install git package for minimal install
  become: yes
  apk:
    update_cache: yes
    name:
      - vim
      - git
      - tmux
      - python3
    state: present

#- debug: var=res
#- meta: end_play    #Usefull for dev: ends the play right here
