---
# tasks file for minimal
#

# Installing basic tools needed for future installs

- name: Install packages for minimal install
  become: yes
  pacman:
    name:
      - base-devel
      - git
    state: present


- name: Check if yay is already present
  command: pacman -Q yay
  changed_when: False
  failed_when: False
  register: is_yay_present

- name: Clone yay repo
  git:
    repo: 'https://aur.archlinux.org/yay.git'
    dest: '/tmp/yay'
    depth: 1
    force: yes
  when: is_yay_present.stdout == ""

- name: Install yay
  command: makepkg -si --noconfirm
  args:
    chdir: /tmp/yay
  when: is_yay_present.stdout == ""


  #  #http://brainxploit.com/2019/03/27/how-to-set-up-avahi-on-arch-linux/
  #- name: Install packages for minimal install
  #  become: yes
  #  pacman:
  #    name:
  #      - avahi
  #      - nss-mdns
  #      - gtk3
  #      - python-dbus
  #      - python-gobject
  #    state: present
  #
  #- name: Set to resolve MDNS names
  #  become: yes
  #  lineinfile:
  #    dest: /etc/nsswitch.conf
  #    state: present
  #    regexp: '^hosts: files mymachines myhostname resolve \[\!UNAVAIL=return\] dns'
  #    line: 'hosts: files mymachines myhostname mdns4_minimal \[NOTFOUND=return\] resolve \[\!UNAVAIL=return\] dns'
  #
  #- name: enable services avahi-daemon and ensure it is not masked
  #  become: yes
  #  systemd:
  #    name: avahi-daemon
  #    state: started
  #    enabled: yes
  #    masked: no
  #
  #- debug: var=res
  #- meta: end_play    #Usefull for dev: ends the play right here
