-- ~/.config/mpv/scripts/beatpulse.lua
--
-- Reads ./track.grid.json next to the audio file.
-- Expects fields:
--   "bpm": 128.0
--   "offset": 0.472
--   "period": 0.46875
--
-- Generated by your bpmgrid.sh -J script.

local mp = require "mp"

local bpm = nil
local offset = nil
local period = nil
local next_beat = nil
local last_beat_index = -1
local enabled = true

local function dirname(path)
    return path:match("^(.*)/[^/]*$") or "."
end

local function basename_noext(path)
    local base = path:match("([^/]+)$") or path
    return base:gsub("%.[^.]*$", "")
end

local function read_file(path)
    local f = io.open(path, "r")
    if not f then return nil end
    local s = f:read("*a")
    f:close()
    return s
end

local function load_grid()
    local path = mp.get_property("path")
    if not path then return end

    local dir = dirname(path)
    local stem = basename_noext(path)
    local gridpath = dir .. "/" .. stem .. ".grid.json"

    local s = read_file(gridpath)
    if not s then
        mp.osd_message("no grid: " .. gridpath, 3)
        return
    end

    bpm = tonumber(s:match('"bpm"%s*:%s*([0-9%.]+)'))
    offset = tonumber(s:match('"offset"%s*:%s*([0-9%.]+)'))
    period = tonumber(s:match('"period"%s*:%s*([0-9%.]+)'))

    if not bpm or not offset or not period then
        mp.osd_message("bad grid json", 3)
        return
    end

    last_beat_index = -1

    mp.osd_message(
        string.format("grid loaded: %.3f BPM / offset %.3f", bpm, offset),
        3
    )
end

local function pulse()
    if not enabled or not bpm or not offset or not period then return end

    local t = mp.get_property_number("time-pos")
    if not t then return end
    if t < offset then return end

    local beat_index = math.floor((t - offset) / period)

    if beat_index ~= last_beat_index then
        last_beat_index = beat_index

        local beat_in_bar = beat_index % 4
        local bar = math.floor(beat_index / 4) + 1

        local msg
        if beat_in_bar == 0 then
            msg = string.format("● BAR %d", bar)
        else
            msg = string.format("• %d", beat_in_bar + 1)
        end

        mp.osd_message(msg, 0.08)
    end
end

local timer = mp.add_periodic_timer(0.01, pulse)

mp.register_event("file-loaded", load_grid)

mp.add_key_binding("b", "toggle-beatpulse", function()
    enabled = not enabled
    if enabled then
        mp.osd_message("beat pulse on", 1)
    else
        mp.osd_message("beat pulse off", 1)
    end
end)
