---
# tasks file for minimal
#


  #source $CONFIG_PERSO/tools/generateBashSpecifics.sh



# Installing basic tools needed for future installs

- name: Install packages for minimal install
  become: yes
  pacman:
    name:
      - base-devel
      - git
    state: present


- name: Check if yay is already present
  command: pacman -Q yay
  changed_when: False
  failed_when: False
  register: is_yay_present

- name: Clone yay repo
  git:
    repo: 'https://aur.archlinux.org/yay.git'
    dest: '/tmp/yay'
    depth: 1
    force: yes
  when: is_yay_present.stdout == ""

- name: Install yay
  command: makepkg -si --noconfirm
  args:
    chdir: /tmp/yay
  when: is_yay_present.stdout == ""


- name: Install packages for minimal install
  become: yes
  pacman:
    name:
      - avahi
    state: present

- name: enable services avahi-daemon and ensure it is not masked
  systemd:
    name: avahi-daemon
    state: started
    enabled: yes
    masked: no

- name: enable services sshd and ensure it is not masked
  systemd:
    name: sshd
    state: started
    enabled: yes
    masked: no


  #- debug: var=res
  #- meta: end_play    #Usefull for dev: ends the play right here
