---
# tasks file for minimal
#

# Installing basic tools needed for future installs


#- name: Allow 'wheel' group to have passwordless sudo
#  lineinfile:
#    dest: /etc/sudoers
#    state: present
#    regexp: '^%wheel'
#    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
#    validate: visudo -cf %s

- name: test perso
  yay:
    name:
      - byobu
  register: res


- debug: var=res

- meta: end_play    #Usefull for dev: ends the play right here


- name: Install packages for minimal install
  become: yes
  pacman:
    name:
      - base-devel
      - git
    state: present

- name: Check if yay is already present
  command: pacman -Q yay
  changed_when: False
  failed_when: False
  register: is_yay_present

- name: Clone yay repo
  git:
    repo: 'https://aur.archlinux.org/yay.git'
    dest: '/tmp/yay'
    depth: 1
    force: yes
  when: is_yay_present.stdout == ""

- name: Install yay
  command: makepkg -si --noconfirm
  args:
    chdir: /tmp/yay
  when: is_yay_present.stdout == ""


#- aur: name=byobu



- name: debug through ansible.env
  debug: var=ansible_env.HOME

- name: Install packages for minimal install
  become: yes
  pacman:
    name:
      - avahi
      - vim
    state: present

- name: enable services avahi-daemon and ensure it is not masked
  systemd:
    name: avahi-daemon
    state: started
    enabled: yes
    masked: no

- name: enable services sshd and ensure it is not masked
  systemd:
    name: sshd
    state: started
    enabled: yes
    masked: no

- name: Configs git usual name
  git_config:
    name: user.name
    scope: global
    value: 'alxndrpsclt'

- name: Configs git usual email
  git_config:
    name: user.email
    scope: global
    value: 'alxndr.psclt@gmail.com'

- name: Configs git editor
  git_config:
    name: core.editor
    scope: global
    value: vim

- name: Clone personal bashconfig and other usefull configs
  git:
    repo: 'https://github.com/AlxndrPsclt/configPerso.git'
    dest: "{{ ansible_env.HOME }}/.config/perso"

- name: Clone personal vimconfig
  git:
    repo: 'https://github.com/AlxndrPsclt/dotvim.git'
    dest: "{{ ansible_env.HOME }}/.vim"

