#!/usr/bin/env zsh

battery_capacity=$(cat /sys/class/power_supply/cw2015-battery/capacity)
battery_status=$(cat /sys/class/power_supply/cw2015-battery/status)

battery_icons=("" "" "" "" "" "")

declare -i level
level="$battery_capacity/20"

if [[ "$battery_status" == "Charging" ]]; then
  message=' '
else
  message=''
fi

notify-send -t 4000 "$message ${battery_icons[$level]} $battery_capacity %"
